#ifndef E_TIMEZONES_HPP
#define E_TIMEZONES_HPP

#include <stdbool.h>
#include <string.h>

struct Timezone {
  const char* name;
  short offsetHours;
  short offsetMinutes;
  bool isPositive;
};

const char timezoneNames[][40] = {"Pacific/Midway",
                                  "Pacific/Honolulu",
                                  "America/Anchorage",
                                  "America/Los_Angeles",
                                  "America/Tijuana",
                                  "America/Phoenix",
                                  "America/Chihuahua",
                                  "America/Denver",
                                  "America/Guatemala",
                                  "America/Chicago",
                                  "America/Mexico_City",
                                  "America/Regina",
                                  "America/Bogota",
                                  "America/New_York",
                                  "America/Caracas",
                                  "America/Halifax",
                                  "America/Santo_Domingo",
                                  "America/Asuncion",
                                  "America/Argentina/Buenos_Aires",
                                  "America/Montevideo",
                                  "America/Godthab",
                                  "Atlantic/South_Georgia",
                                  "Atlantic/Azores",
                                  "Atlantic/Cape_Verde",
                                  "Africa/Casablanca",
                                  "Europe/London",
                                  "Europe/Lisbon",
                                  "Africa/Monrovia",
                                  "Etc/UTC",
                                  "Europe/Amsterdam",
                                  "Europe/Belgrade",
                                  "Europe/Bratislava",
                                  "Europe/Budapest",
                                  "Europe/Prague",
                                  "Europe/Warsaw",
                                  "Europe/Sarajevo",
                                  "Europe/Skopje",
                                  "Europe/Zagreb",
                                  "Europe/Brussels",
                                  "Europe/Copenhagen",
                                  "Europe/Madrid",
                                  "Europe/Paris",
                                  "Europe/Berlin",
                                  "Europe/Rome",
                                  "Europe/Stockholm",
                                  "Europe/Vienna",
                                  "Africa/Algiers",
                                  "Europe/Bucharest",
                                  "Africa/Cairo",
                                  "Europe/Helsinki",
                                  "Europe/Kiev",
                                  "Europe/Riga",
                                  "Europe/Sofia",
                                  "Europe/Tallinn",
                                  "Europe/Vilnius",
                                  "Europe/Athens",
                                  "Europe/Istanbul",
                                  "Europe/Minsk",
                                  "Asia/Jerusalem",
                                  "Africa/Harare",
                                  "Africa/Johannesburg",
                                  "Europe/Moscow",
                                  "Asia/Baghdad",
                                  "Asia/Kuwait",
                                  "Africa/Nairobi",
                                  "Asia/Riyadh",
                                  "Europe/Volgograd",
                                  "Asia/Tehran",
                                  "Asia/Muscat",
                                  "Asia/Baku",
                                  "Asia/Tbilisi",
                                  "Asia/Yerevan",
                                  "Asia/Kabul",
                                  "Asia/Karachi",
                                  "Asia/Tashkent",
                                  "Asia/Yekaterinburg",
                                  "Asia/Calcutta",
                                  "Asia/Colombo",
                                  "Asia/Katmandu",
                                  "Asia/Almaty",
                                  "Asia/Dhaka",
                                  "Asia/Yangon",
                                  "Asia/Bangkok",
                                  "Asia/Krasnoyarsk",
                                  "Asia/Hong_Kong",
                                  "Asia/Kuala_Lumpur",
                                  "Asia/Taipei",
                                  "Australia/Perth",
                                  "Asia/Irkutsk",
                                  "Asia/Ulaanbaatar",
                                  "Asia/Seoul",
                                  "Asia/Tokyo",
                                  "Asia/Yakutsk",
                                  "Australia/Darwin",
                                  "Australia/Adelaide",
                                  "Australia/Sydney",
                                  "Australia/Brisbane",
                                  "Australia/Hobart",
                                  "Pacific/Guam",
                                  "Pacific/Port_Moresby",
                                  "Asia/Vladivostok",
                                  "Pacific/Fiji",
                                  "Pacific/Auckland",
                                  "Pacific/Tongatapu",
                                  "Pacific/Kiritimati",
                                  "Pacific/Apia",
                                  "Pacific/Enderbury",
                                  "Pacific/Fakaofo",
                                  "Pacific/Fiji",
                                  "Pacific/Funafuti",
                                  "Pacific/Galapagos",
                                  "Pacific/Gambier",
                                  "Pacific/Guadalcanal",
                                  "Pacific/Guam",
                                  "Pacific/Honolulu",
                                  "Pacific/Johnston",
                                  "Pacific/Kiritimati",
                                  "Pacific/Kosrae",
                                  "Pacific/Kwajalein",
                                  "Pacific/Majuro",
                                  "Pacific/Marquesas",
                                  "Pacific/Midway",
                                  "Pacific/Nauru",
                                  "Pacific/Niue",
                                  "Pacific/Norfolk",
                                  "Pacific/Noumea",
                                  "Pacific/Pago_Pago",
                                  "Pacific/Palau",
                                  "Pacific/Pitcairn",
                                  "Pacific/Pohnpei",
                                  "Pacific/Port_Moresby",
                                  "Pacific/Rarotonga",
                                  "Pacific/Saipan",
                                  "Pacific/Tahiti",
                                  "Pacific/Tarawa",
                                  "Pacific/Tongatapu",
                                  "Pacific/Wake",
                                  "Pacific/Wallis"};

typedef enum {
  // -11:00
  MIDWAY_ISLAND,
  // -10:00
  HAWAII,
  // -09:00
  ALASKA,
  // -08:00
  PACIFIC_TIME,
  TIJUANA,
  // -07:00
  ARIZONA,
  MOUNTAIN_TIME,
  // -06:00
  EL_SALVADOR,
  CHIHUAHUA,
  CENTRAL_TIME,
  MEXICO_CITY,
  SASKATCHEWAN,
  TEGUCIGALPA,
  SAN_JOSE,
  GUATEMALA_CITY,
  // -05:00
  BOGOTA,
  EASTERN_TIME,
  WASHINGTON_DC,
  KINGSTON,
  QUITO,
  PORT_AU_PRINCE,
  LIMA,
  PANAMA,
  // -04:00
  PUERTO_RICO,
  CARACAS,
  ATLANTIC_TIME,
  MANAUS,
  LA_PAZ,
  SANTO_DOMINGO,
  GUYANA,
  // -03:00
  NEWFOUNDLAND,
  SANTIAGO,
  BRASILIA,
  BUENOS_AIRES,
  MONTEVIDEO,
  ASUNCION,
  // -02:00
  GREENLAND,
  MID_ATLANTIC,
  // -01:00
  AZORES,
  CAPE_VERDE,
  // 00:00
  BISSAU,
  BAMAKO,
  ACCRA,
  YAMOUSSOUKRO,
  OUAGADOUGOU,
  NOUAKCHOTT,
  LISBON,
  RABAT_CASABLANCA,
  CONAKRY,
  LOME,
  DAKAR,
  MONROVIA,
  FREETOWN,
  LONDON_DUBLIN,
  BANJUL,
  // +01:00
  AMSERDAM,
  BELGRADE,
  BRUSSELS,
  SARAJEVO,
  LAGOS,
  DOUALA_YAOUNDE,
  LIBVREVILLE,
  BRAZZAVILLE,
  ALGIERS,
  PORTO_NOVO,
  NIAMEY,
  N_DJAMENA,  // N'Djamena
  LUANDA,
  TUNIS,
  MALABO,
  BANGUI,
  MADRID,
  ROME,
  BERLIN,
  PARIS,
  KINSHASA,
  PRAQUE,
  ZAGREB,
  LJUBLJANA,
  VIENNA,
  // +02:00
  ATHENS,
  BEIRUT_LEBANON,
  HELSINKI,
  JERUSALEM,
  WINDHOEK,
  LUBUMBASHI,
  LUSAKA,
  HARARE,
  TRIPOLI,
  MAPUTO,
  KIGALI,
  CAIRO,
  JOHANNESBURG,
  LILONGWE,
  GABORONE,
  BUJUMBURA,
  KHARTOUM,
  KILININGRAD,
  JUBA,
  KYIV,
  CAPE_TOWN,
  SOFIA,
  NICOSIA,
  // +03:00
  AMMAN_JORDAN,
  MINSK,
  MOSCOW,
  KUWAIT,
  ANKARA,
  ANTANANARIVO,
  DODOMA,
  NAIROBI,
  KAMPALA,
  ADDIS_ABABA,
  MOGADISHU,
  RIYADH,
  BAGHDAD,
  DJIBOUTI,
  DAMASCUS,
  DOHA,
  SANAA,
  BAHRAIN,
  TEHRAN,
  // +04:00
  BAKU,
  TBILISI,
  YEREVAN,
  PORT_LOUIS,
  ABU_DHABI,
  VICTORIA,
  SAMARA,
  MUSSCAT,
  // +04:30
  KABUL,
  // +05:00
  URALSK,
  YEKATERINBURG,
  ASTANA,
  ISLAMABAD_KARACHI,
  TASHKENT,
  // +05:30
  KOLKATA,
  NEW_DELHI,
  COLOMBO,
  // +05:45
  KATHMANDU,
  // +06:00
  DHAKA,
  OMSK,
  BISHKEK,
  // +06:30
  YANGON,
  // +07:00
  KRASNOYARSK,
  BANGKOK,
  JAKARTA,
  HANOI,
  PHNOM_PENH,
  NOVOSSIBIRSK,
  VIENTIANE,
  PONTIANAK,
  // +08:00
  IRKUTSK,
  PERTH,
  TAIPEI,
  KUALA_LUMPUR,
  MANILA,
  BEIJING,
  HONG_KONG,
  SINGAPORE,
  BANDAR_SERI_BEGAWAN,
  MAKASSAR,
  // +09:00
  SEOUL,
  TOKYO_OSAKA,
  YAKUTSK,
  CHITA,
  DILI,
  JAYAPURA,
  // +09:30
  DARWIN,
  // +10:00
  BRISBANE,
  VLADIVOSTOK,
  GUAM,
  PORT_MORESBY,
  // +10:30
  ADELAIDE,
  // +11:00
  HOBART,
  SYDNEY_CANBERRA,
  MAGADAN,
  YUZHNO_SAKHALINSK,
  GUADALCANAL,
  EFATE,
  // +12:00
  MARSHALL_ISLANDS,
  FIJI,
  KAMCHATKA_PENINSULA,
  ANADYR,
  TARAWA,
  // +13:00
  AUCKLAND,
  TONGA,
  ENDERBURY,
  APIA,
  // +14:00
  KIRITIMATI,
} ETimezones;

// Return the string representation of the time e.g. "+03:00"
const char* getTimezoneString(ETimezones timezone);

// Return the name of that timezone e.g. "GMT +3:00"
// TODO: Later return the name of the timezone e.g. "Africa/Nairobi"
const char* getTimezoneName(ETimezones timezone);
#endif  // E_TIMEZONES_HPP
