#ifndef CONFIG_HPP_
#define CONFIG_HPP_

// IO
#define S3_PHONE_ANALOG_RESOLUTION 12

// GSM
#define GSM_RX 4
#define GSM_TX 5
#define GSM_BAUD 9600

// Display (ILI9341) - Touch (XPT2046)
#define TFT_CS 15
#define TFT_RST 16
#define TFT_DC 17
#define TFT_MISO 9
#define TFT_MOSI 18
#define TFT_CLK 8
#define TFT_LED 3
#define TOUCH_CLK TFT_CLK
#define TOUCH_CS 10
#define TOUCH_DIN TFT_MOSI
#define TOUCH_DO TFT_MISO

#define CALIBRATION_DATA \
  { 282, 433, 252, 3865, 3815, 438, 3833, 3878 }

#define TFT_WIDTH 240
#define TFT_HEIGHT 320
#define TFT_DRAW_BUF_SIZE (TFT_WIDTH * TFT_HEIGHT / 10 * (LV_COLOR_DEPTH / 8))

// File System
#define FILESYSTEM_FORMAT_ON_FAIL 1

#define FS_SETTINGS_DISPLAY_FILEPATH "/system/settings/display.json"
#define FS_SETTINGS_THEMES_FILEPATH "/system/settings/themes.json"

#define FS_VAR_SETTINGS_DISPLAY_BRIGHTNESS "brightness"
#define FS_DEF_SETTINGS_DISPLAY_BRIGHTNESS "120"
#define FS_VAR_SETTINGS_DISPLAY_TIMEOUT "timeout"
#define FS_DEF_SETTINGS_DISPLAY_TIMEOUT "15"

#define FS_VAR_SETTINGS_THEMES_THEME_DARK "dark"
#define FS_DEF_SETTINGS_THEMES_THEME_DARK "0"
#define FS_VAR_SETTINGS_THEMES_WALLPAPER "wallpaper"
#define FS_DEF_SETTINGS_THEMES_WALLPAPER "1"


#endif  // CONFIG_HPP_
