// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: s3-phone

#ifndef _S3_PHONE_UI_H
#define _S3_PHONE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include <CustomSymbols.hpp>

#include "ui_events.h"
#include "ui_helpers.h"
#include "ui_utils.h"

// SCREEN: ui_homeScreen
void ui_homeScreen_screen_init(void);
extern lv_obj_t* ui_homeScreen;
extern lv_obj_t* ui_imgHomeWallpaper;
extern lv_obj_t* ui_panelMain;
extern lv_obj_t* ui_barHomeSignalLevel;
extern lv_obj_t* ui_lblHomeBatteryLevel;
void ui_event_lblHomeTime(lv_event_t* e);
extern lv_obj_t* ui_lblHomeTime;
extern lv_obj_t* ui_lblHomeDate;
void ui_event_lblHomeMenu(lv_event_t* e);
extern lv_obj_t* ui_lblHomeMenu;
extern lv_obj_t* ui_lblHomeContacts;
extern lv_obj_t* ui_lblHomeISP;
// SCREEN: ui_mainMenuScreen
void ui_mainMenuScreen_screen_init(void);
extern lv_obj_t* ui_mainMenuScreen;
extern lv_obj_t* ui_mainMenuPanel;
extern lv_obj_t* ui_menuMainContainer;
extern lv_obj_t* ui_imbContacts;
extern lv_obj_t* ui_imbMessages;
extern lv_obj_t* ui_imbCallHistory;
extern lv_obj_t* ui_imbSettings;
extern lv_obj_t* ui_imbMultimedia;
extern lv_obj_t* ui_imbExtra;
extern lv_obj_t* ui_imbGames;
extern lv_obj_t* ui_imbMyZone;
extern lv_obj_t* ui_imbAbout;
extern lv_obj_t* ui_bottomBar;
void ui_event_lblMainMenuBack(lv_event_t* e);
extern lv_obj_t* ui_lblMainMenuBack;
void ui_event_lblHomeContacts(lv_event_t* e);
// SCREEN: ui_contactsScreen
void ui_contactsScreen_screen_init(void);
extern lv_obj_t* ui_contactsScreen;
extern lv_obj_t* ui_panelContactMain;
extern lv_obj_t* ui_lblContactTitle;
extern lv_obj_t* ui_listContact;
extern void ui_event_listContact(lv_event_t* e);
extern lv_obj_t* ui_lblContactBack;
void ui_event_lblContactBack(lv_event_t* e);
// SCREEN: ui_contactDetailsScreen
void ui_contactDetailsScreen_screen_init(void);
extern lv_obj_t* ui_contactDetailsScreen;
extern lv_obj_t* ui_panelContactDetails;
extern lv_obj_t* ui_lblContactDetailsTitle;
extern lv_obj_t* ui_listContactDetailsOptions;
extern lv_obj_t* ui_lblContactDetailsBack;
void ui_event_listContactDetailsOptions(lv_event_t* e);
void ui_event_lblContactDetailsBack(lv_event_t* e);
extern lv_obj_t* ui_lblContactBack;
// SCREEN: ui_simPinScreen
void ui_simPinScreen_screen_init(void);
extern lv_obj_t* ui_simPinScreen;
extern lv_obj_t* ui_txtPinPinScreen;
extern lv_obj_t* ui_btnOkPinPinScreen;
extern lv_obj_t* ui_lblOkPinPinScreen;
extern lv_obj_t* ui_lblUnlockPhonePinScreen;
void ui_event_btnOkPinPinScreen(lv_event_t* e);
extern lv_obj_t* ui_btnMatrixNumPinScreen;
extern void ui_event_btnMatrixNumHandler(lv_event_t* e);

// SCREEN: ui_alarmMainScreen
void ui_alarmMainScreen_screen_init(void);
extern lv_obj_t* ui_alarmMainScreen;
extern lv_obj_t* ui____initial_actions0;
// SCREEN: ui_splashScreen
void ui_splashScreen_screen_init(void);
extern lv_obj_t* ui_splashScreen;
extern lv_obj_t* ui____initial_actions0;
// SCREEN: ui_contactAddScreen
void ui_contactAddScreen_screen_init(void);
extern lv_obj_t* ui_contactAddScreen;
extern lv_obj_t* ui_contactAddPanel;
extern lv_obj_t* ui_lblContactAddName;
extern lv_obj_t* ui_txtContactAddName;
extern lv_obj_t* ui_lblContactAddNumber;
extern lv_obj_t* ui_txtContactAddNumber;
extern lv_obj_t* ui_lblContactAddSaveTo;
extern lv_obj_t* ui_dropDownContactAddSaveTo;
extern lv_obj_t* ui_lblContactAddSave;
extern lv_obj_t* ui_lblContactAddDiscard;
extern lv_obj_t* ui_lblContactAddBack;
void ui_event_fabContactAdd(lv_event_t* e);
void ui_event_lblContactAddSave(lv_event_t* e);
void ui_event_lblContactAddDiscard(lv_event_t* e);
// General UI events
extern lv_obj_t* ui_keyboard_full;
extern lv_obj_t* ui_keyboard_num;
void ui_event_textArea_full_cb(lv_event_t* e);
void ui_event_textArea_num_cb(lv_event_t* e);
void ui_event_keyboard_full_event_cb(lv_event_t* e);
void ui_event_keyboard_num_event_cb(lv_event_t* e);

extern lv_obj_t* ui____initial_actions0;

LV_IMG_DECLARE(ui_img_nature_png);             // assets/nature.png
LV_IMG_DECLARE(ui_img_phone_png);              // assets/phone.png
LV_IMG_DECLARE(ui_img_email_png);              // assets/email.png
LV_IMG_DECLARE(ui_img_617275014);              // assets/phone-call.png
LV_IMG_DECLARE(ui_img_settings_png);           // assets/settings.png
LV_IMG_DECLARE(ui_img_multimedia_png);         // assets/multimedia.png
LV_IMG_DECLARE(ui_img_target_png);             // assets/target.png
LV_IMG_DECLARE(ui_img_335818912);              // assets/game-controller.png
LV_IMG_DECLARE(ui_img_info_png);               // assets/info.png
LV_IMG_DECLARE(ui_lottie_load_circular);       // binary lottie file
LV_IMG_DECLARE(ui_lottie_load_circular_lines)  // binary lottie file

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
