// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: s3-phone

#ifndef _S3_PHONE_UI_H
#define _S3_PHONE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_events.h"
#include "ui_helpers.h"

// SCREEN: ui_homeScreen
void ui_homeScreen_screen_init(void);
extern lv_obj_t* ui_homeScreen;
extern lv_obj_t* ui_imgHomeWallpaper;
extern lv_obj_t* ui_panelMain;
extern lv_obj_t* ui_barHomeSignalLevel;
extern lv_obj_t* ui_lblHomeBatteryLevel;
void ui_event_lblHomeTime(lv_event_t* e);
extern lv_obj_t* ui_lblHomeTime;
extern lv_obj_t* ui_lblHomeDate;
void ui_event_lblHomeMenu(lv_event_t* e);
extern lv_obj_t* ui_lblHomeMenu;
extern lv_obj_t* ui_lblHomeContacts;
extern lv_obj_t* ui_lblHomeISP;
// SCREEN: ui_mainMenuScreen
void ui_mainMenuScreen_screen_init(void);
extern lv_obj_t* ui_mainMenuScreen;
extern lv_obj_t* ui_mainMenuPanel;
extern lv_obj_t* ui_menuMainContainer;
extern lv_obj_t* ui_imbContacts;
extern lv_obj_t* ui_imbMessages;
extern lv_obj_t* ui_imbCallHistory;
extern lv_obj_t* ui_imbSettings;
extern lv_obj_t* ui_imbMultimedia;
extern lv_obj_t* ui_imbExtra;
extern lv_obj_t* ui_imbGames;
extern lv_obj_t* ui_imbMyZone;
extern lv_obj_t* ui_imbAbout;
extern lv_obj_t* ui_bottomBar;
void ui_event_lblMainMenuBack(lv_event_t* e);
extern lv_obj_t* ui_lblMainMenuBack;
// SCREEN: ui_contactsScreen
void ui_contactsScreen_screen_init(void);
extern lv_obj_t* ui_contactsScreen;
extern lv_obj_t* ui_panelContactMain;
extern lv_obj_t* ui_lblContactTitle;
extern lv_obj_t* ui_listContact;
// SCREEN: ui_alarmMainScreen
void ui_alarmMainScreen_screen_init(void);
extern lv_obj_t* ui_alarmMainScreen;
extern lv_obj_t* ui____initial_actions0;

LV_IMG_DECLARE(ui_img_nature_png);      // assets/nature.png
LV_IMG_DECLARE(ui_img_phone_png);       // assets/phone.png
LV_IMG_DECLARE(ui_img_email_png);       // assets/email.png
LV_IMG_DECLARE(ui_img_617275014);       // assets/phone-call.png
LV_IMG_DECLARE(ui_img_settings_png);    // assets/settings.png
LV_IMG_DECLARE(ui_img_multimedia_png);  // assets/multimedia.png
LV_IMG_DECLARE(ui_img_target_png);      // assets/target.png
LV_IMG_DECLARE(ui_img_335818912);       // assets/game-controller.png
LV_IMG_DECLARE(ui_img_info_png);        // assets/info.png

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
