#ifndef UI_CONSTANTS_H_
#define UI_CONSTANTS_H_

#define UI_ANIMATION_DURATION 150  //< Animation duration in milliseconds>
#define UI_TRANSPARENCY 100        //< Transparency level>

#define UI_ALIGN_TOP_LEFT_X_OFFSET -15
#define UI_ALIGN_TOP_LEFT_Y_OFFSET -15

/**
 *@brief For events handling and screen navigation
 */
typedef enum {
  SCREEN_SPLASH = 0,  //< Splash screen when booting>
  SCREEN_HOME,
  SCREEN_MAIN_MENU,
  SCREEN_PHONE,  //< Phone screen with dialer>
  SCREEN_CONTACTS,
  SCREEN_CONTACT_OPTIONS,
  SCREEN_CONTACT_DETAILS,
  SCREEN_CONTACT_ADD,
  SCREEN_CONTACT_EDIT,
  SCREEN_MESSAGES,
  SCREEN_MESSAGE_READ,
  SCREEN_MESSAGE_COMPOSE,
  SCREEN_SIM_PIN_UNLOCK,
  SCREEN_ALARM_MAIN,
  SCREEN_ALARM_ADD,
  SCREEN_ALARM_DETAILS,
  SCREEN_SETTINGS,
  SCREEN_SETTINGS_CONNECTIVITY,
  SCREEN_SETTINGS_NETWORK_INTERNET,
  SCREEN_SETTINGS_DISPLAY,
  SCREEN_SETTINGS_WALLPAPERS_THEMES,
  SCREEN_SETTINGS_LOCK_SCREEN_SECURITY,
  SCREEN_SETTINGS_SOUND,
  SCREEN_SETTINGS_STORAGE,
  SCREEN_SETTINGS_SYSTEM,
  SCREEN_SETTINGS_ABOUT,
  SCREEN_SETTINGS_RESET,
  SCREEN_SETTINGS_RESET_CONFIRM,
  SCREEN_SETTINGS_RESET_SUCCESS,
  SCREEN_SETTINGS_RESET_FAIL,
  SCREEN_SETTINGS_RESET_FAIL_NO_SIM,
  SCREEN_SETTINGS_RESET_FAIL_NO_SD
} s3_screens_t;

typedef enum {
  TIMEOUT_5_SEC = 5,
  TIMEOUT_10_SEC = 10,
  TIMEOUT_15_SEC = 15,
  TIMEOUT_30_SEC = 30,
  TIMEOUT_1_MIN = 1 * 60,
  TIMEOUT_2_MIN = 2 * 60,
  TIMEOUT_5_MIN = 5 * 60,
  TIMEOUT_10_MIN = 10 * 60,
  TIMEOUT_NEVER = 0,
} s3_screen_timeout_t;

typedef enum  {
  DROP_TIMEOUT_5_SEC = 0,
  DROP_TIMEOUT_10_SEC = 1,
  DROP_TIMEOUT_15_SEC = 2,
  DROP_TIMEOUT_30_SEC = 3,
  DROP_TIMEOUT_1_MIN = 4,
  DROP_TIMEOUT_2_MIN = 5,
  DROP_TIMEOUT_5_MIN = 6,
  DROP_TIMEOUT_10_MIN = 7,
  DROP_TIMEOUT_NEVER = 8,
} s3_screen_timeout_index_t;

typedef enum {
  S3_IMG_BACKGROUND_BEAUTIFUL_SUNSET = 1,
  S3_IMG_BACKGROUND_DOCK_SUNSET,
  S3_IMG_BACKGROUND_NATURE_FOOTPATH,
  S3_IMG_BACKGROUND_GREEN_LAKE,
  S3_IMG_BACKGROUND_GREEN_FOREST,
} s3_resource_num_t;

#endif  // UI_CONSTANTS_H_
