#pragma once

#define UI_ANIMATION_DURATION 150  //< Animation duration in milliseconds>
#define UI_TRANSPARENCY 100        //< Transparency level>

/**
 *@brief For events handling and screen navigation
 */
enum SCREENS {
  SCREEN_SPLASH = 0,  //< Splash screen when booting>
  SCREEN_HOME,
  SCREEN_MAIN_MENU,
  SCREEN_PHONE,  //< Phone screen with dialer>
  SCREEN_CONTACTS,
  SCREEN_CONTACT_OPTIONS,
  SCREEN_CONTACT_DETAILS,
  SCREEN_CONTACT_ADD,
  SCREEN_CONTACT_EDIT,
  SCREEN_MESSAGES,
  SCREEN_MESSAGE_READ,
  SCREEN_MESSAGE_COMPOSE,
  SCREEN_SIM_PIN_UNLOCK,
  SCREEN_ALARM_MAIN,
  SCREEN_ALARM_ADD,
  SCREEN_ALARM_DETAILS,
  SCREEN_SETTINGS,
  SCREEN_SETTINGS_DISPLAY,
  SCREEN_SETTINGS_SOUND,
  SCREEN_SETTINGS_NETWORK,
  SCREEN_SETTINGS_SECURITY,
  SCREEN_SETTINGS_ABOUT,
  SCREEN_SETTINGS_RESET,
  SCREEN_SETTINGS_RESET_CONFIRM,
  SCREEN_SETTINGS_RESET_SUCCESS,
  SCREEN_SETTINGS_RESET_FAIL,
  SCREEN_SETTINGS_RESET_FAIL_NO_SIM,
  SCREEN_SETTINGS_RESET_FAIL_NO_SD
};
