// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: s3-phone

#include "ui.h"

#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_homeScreen
void ui_homeScreen_screen_init(void);
lv_obj_t* ui_homeScreen;
lv_obj_t* ui_imgHomeWallpaper;
lv_obj_t* ui_panelMain;
lv_obj_t* ui_barHomeSignalLevel;
lv_obj_t* ui_lblHomeBatteryLevel;
void ui_event_lblHomeTime(lv_event_t* e);
lv_obj_t* ui_lblHomeTime;
lv_obj_t* ui_lblHomeDate;
void ui_event_lblHomeMenu(lv_event_t* e);
lv_obj_t* ui_lblHomeMenu;
lv_obj_t* ui_lblHomeContacts;
lv_obj_t* ui_lblHomeISP;

// SCREEN: ui_mainMenuScreen
void ui_mainMenuScreen_screen_init(void);
lv_obj_t* ui_mainMenuScreen;
lv_obj_t* ui_mainMenuPanel;
lv_obj_t* ui_menuMainContainer;
lv_obj_t* ui_imbContacts;
lv_obj_t* ui_imbMessages;
lv_obj_t* ui_imbCallHistory;
lv_obj_t* ui_imbSettings;
lv_obj_t* ui_imbMultimedia;
lv_obj_t* ui_imbExtra;
lv_obj_t* ui_imbGames;
lv_obj_t* ui_imbMyZone;
lv_obj_t* ui_imbAbout;
lv_obj_t* ui_bottomBar;
void ui_event_lblMainMenuBack(lv_event_t* e);
lv_obj_t* ui_lblMainMenuBack;
void ui_event_listContact(lv_event_t* e);
void ui_event_lblContactBack(lv_event_t* e);
lv_obj_t* ui_lblContactBack;

// SCREEN: ui_contactsScreen
void ui_contactsScreen_screen_init(void);
lv_obj_t* ui_contactsScreen;
lv_obj_t* ui_panelContactMain;
lv_obj_t* ui_lblContactTitle;
lv_obj_t* ui_listContact;
lv_obj_t* ui_lblContactBack;
void ui_event_listContact(lv_event_t* e);
lv_obj_t* ui_lblMainMenuBack;

// SCREEN: ui_alarmMainScreen
void ui_alarmMainScreen_screen_init(void);
lv_obj_t* ui_alarmMainScreen;
lv_obj_t* ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_lblHomeTime(lv_event_t* e) {
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t* target = lv_event_get_target(e);
  if (event_code == LV_EVENT_CLICKED) {
    _ui_screen_change(&ui_alarmMainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0,
                      &ui_alarmMainScreen_screen_init);
  }
}
void ui_event_lblHomeMenu(lv_event_t* e) {
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t* target = lv_event_get_target(e);
  if (event_code == LV_EVENT_CLICKED) {
    _ui_screen_change(&ui_mainMenuScreen, LV_SCR_LOAD_ANIM_MOVE_TOP, 300, 0,
                      &ui_mainMenuScreen_screen_init);
  }
}
void ui_event_lblHomeContacts(lv_event_t* e) {
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t* target = lv_event_get_target(e);
  if (event_code == LV_EVENT_CLICKED) {
    _ui_screen_change(&ui_contactsScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 300, 0,
                      &ui_contactsScreen_screen_init);
  }
}
void ui_event_lblMainMenuBack(lv_event_t* e) {
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t* target = lv_event_get_target(e);
  if (event_code == LV_EVENT_CLICKED) {
    _ui_screen_change(&ui_homeScreen, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 300, 0,
                      &ui_homeScreen_screen_init);
  }
}

void ui_event_lblContactBack(lv_event_t* e) {
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t* target = lv_event_get_target(e);
  if (event_code == LV_EVENT_CLICKED) {
    _ui_screen_change(&ui_homeScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 300, 0,
                      &ui_homeScreen_screen_init);
  }
}

void ui_event_listContact(lv_event_t* e) {
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t* target = lv_event_get_target(e);
  if (event_code == LV_EVENT_CLICKED) {
    LV_LOG_USER("Clicked", lv_list_get_button_text(target));
    // DEBUG_PRINTF("Clicked: %s\n", lv_list_get_button_text(target));
  }
}

///////////////////// SCREENS ////////////////////

void ui_init(void) {
  lv_disp_t* dispp = lv_display_get_default();
  lv_theme_t* theme = lv_theme_default_init(
      dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
      false, LV_FONT_DEFAULT);
  lv_disp_set_theme(dispp, theme);
  ui_homeScreen_screen_init();
  ui_mainMenuScreen_screen_init();
  ui_contactsScreen_screen_init();
  ui_alarmMainScreen_screen_init();
  ui____initial_actions0 = lv_obj_create(NULL);
  lv_disp_load_scr(ui_homeScreen);
}
