// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: s3-phone

#include "ui.h"

#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_homeScreen
void ui_homeScreen_screen_init(void);
lv_obj_t* ui_homeScreen;
lv_obj_t* ui_panelMain;
lv_obj_t* ui_homeContainerTopBar;
lv_obj_t* ui_lblHomeBatteryLevel;
lv_obj_t* ui_lblHomeSignalLevel;
lv_obj_t* ui_homeContainerDateISP;
void ui_event_lblHomeTime(lv_event_t* e);
lv_obj_t* ui_lblHomeTime;
lv_obj_t* ui_lblHomeDate;
lv_obj_t* ui_lblHomeISP;
lv_obj_t* ui_homeContainerStart;
lv_obj_t* ui_imbHomePhone;
lv_obj_t* ui_imbHomeMessages;
void ui_event_imbClickEvent(lv_event_t* e);
lv_obj_t* ui_imbHomeApps;
lv_obj_t* ui_imbHomeBrowser;
lv_obj_t* ui_imbHomeContacts;

// SCREEN: ui_mainMenuScreen
void ui_mainMenuScreen_screen_init(void);
lv_obj_t* ui_mainMenuScreen;
lv_obj_t* ui_panelMainMenu;
lv_obj_t* ui_menuMainContainer;
lv_obj_t* ui_menuPhoneContainer;
lv_obj_t* ui_imbPhone;
lv_obj_t* ui_lblMenuPhone;
lv_obj_t* ui_menuMessagesContainer;
lv_obj_t* ui_imbMessages;
lv_obj_t* ui_lblMenuMessages;
lv_obj_t* ui_menuMultimediaContainer;
lv_obj_t* ui_imbMultimedia;
lv_obj_t* ui_lblMenuMultimedia;
lv_obj_t* ui_menuExtraContainer;
lv_obj_t* ui_imbExtra;
lv_obj_t* ui_lblMenuExtra;
lv_obj_t* ui_menuGamesContainer;
lv_obj_t* ui_imbGames;
lv_obj_t* ui_lblMenuGames;
lv_obj_t* ui_menuMyZoneContainer;
lv_obj_t* ui_imbMyZone;
lv_obj_t* ui_lblMenuMyZone;
lv_obj_t* ui_menuAboutContainer;
lv_obj_t* ui_imbAbout;
lv_obj_t* ui_lblMenuAbout;
lv_obj_t* ui_menuToolsContainer;
lv_obj_t* ui_imbTools;
lv_obj_t* ui_lblMenuTools;
lv_obj_t* ui_bottomBar;
void ui_event_evtBottombar(lv_event_t* e);
lv_obj_t* ui_lblBottombarTasks;
lv_obj_t* ui_lblBottombarHome;
lv_obj_t* ui_lblBottombarBack;

// SCREEN: ui_contactsScreen
void ui_contactsScreen_screen_init(void);
lv_obj_t* ui_contactsScreen;
lv_obj_t* ui_panelContactMain;
lv_obj_t* ui_lblContactTitle;
lv_obj_t* ui_listContact;
lv_obj_t* ui_lblContactBack;
void ui_event_listContact(lv_event_t* e);
void ui_event_lblContactBack(lv_event_t* e);

// SCREEN: ui_contactDetailsScreen
void ui_contactDetailsScreen_screen_init(void);
lv_obj_t* ui_contactDetailsScreen;
lv_obj_t* ui_panelContactDetails;
lv_obj_t* ui_lblContactDetailsTitle;
lv_obj_t* ui_listContactDetailsOptions;
lv_obj_t* ui_lblContactDetailsBack;
void ui_event_lblContactDetailsBack(lv_event_t* e);
void ui_event_listContactDetailsOptions(lv_event_t* e);

// SCREEN: ui_simPinScreen
void ui_simPinScreen_screen_init(void);
lv_obj_t* ui_simPinScreen;
lv_obj_t* ui_txtPinPinScreen;
lv_obj_t* ui_btnOkPinPinScreen;
lv_obj_t* ui_lblOkPinPinScreen;
lv_obj_t* ui_lblUnlockPhonePinScreen;
void ui_event_btnOkPinPinScreen(lv_event_t* e);
lv_obj_t* ui_btnMatrixNumPinScreen;
void ui_event_btnMatrixNumHandler(lv_event_t* e);

// SCREEN: ui_alarmMainScreen
void ui_alarmMainScreen_screen_init(void);
lv_obj_t* ui_alarmMainScreen;
lv_obj_t* ui____initial_actions0;

// SCREEN: ui_splashScreen
void ui_splashScreen_screen_init(void);
lv_obj_t* ui_splashScreen;
// SCREEN: ui_contactAddScreen
void ui_contactAddScreen_screen_init(void);
lv_obj_t* ui_contactAddScreen;
lv_obj_t* ui_panelContactAdd;
lv_obj_t* ui_lblContactAddName;
lv_obj_t* ui_txtContactAddName;
lv_obj_t* ui_lblContactAddNumber;
lv_obj_t* ui_txtContactAddNumber;
lv_obj_t* ui_lblContactAddSaveTo;
lv_obj_t* ui_dropDownContactAddSaveTo;
lv_obj_t* ui_lblContactAddSave;
lv_obj_t* ui_lblContactAddDiscard;
lv_obj_t* ui_lblContactAddBack;
void ui_event_fabContactAdd(lv_event_t* e);
void ui_event_lblContactAddSave(lv_event_t* e);
void ui_event_lblContactAddDiscard(lv_event_t* e);

// General UI
lv_obj_t* ui_keyboard_full;
lv_obj_t* ui_keyboard_num;
void ui_event_textArea_full_cb(lv_event_t* e);
void ui_event_textArea_num_cb(lv_event_t* e);
void ui_event_keyboard_full_event_cb(lv_event_t* e);
void ui_event_keyboard_num_event_cb(lv_event_t* e);

lv_obj_t* ui____initial_actions0;

const lv_image_dsc_t* ui_imgset_usergroup[1] = {&ui_img_usergroup40_png};
const lv_image_dsc_t* ui_imgset_browser[1] = {&ui_img_browser40_png};
const lv_image_dsc_t* ui_imgset_callgreen[1] = {&ui_img_callgreen40_png};
const lv_image_dsc_t* ui_imgset_callred[1] = {&ui_img_callred40_png};
const lv_image_dsc_t* ui_imgset_phoneblue[1] = {&ui_img_phoneblue40_png};
const lv_image_dsc_t* ui_imgset_dropzone[1] = {&ui_img_dropzone40_png};
const lv_image_dsc_t* ui_imgset_simcard[1] = {&ui_img_simcard40_png};
const lv_image_dsc_t* ui_imgset_outdatedphone[1] = {
    &ui_img_outdatedphone40_png};
const lv_image_dsc_t* ui_imgset_about[1] = {&ui_img_about40_png};
const lv_image_dsc_t* ui_imgset_extra[1] = {&ui_img_extra40_png};
const lv_image_dsc_t* ui_imgset_messages[1] = {&ui_img_messages40_png};
const lv_image_dsc_t* ui_imgset_openphone[1] = {&ui_img_openphone40_png};
const lv_image_dsc_t* ui_imgset_multimedia[1] = {&ui_img_multimedia40_png};
const lv_image_dsc_t* ui_imgset_games[1] = {&ui_img_games40_png};
const lv_image_dsc_t* ui_imgset_phonered[1] = {&ui_img_phonered40_png};
const lv_image_dsc_t* ui_imgset_phonebluee[1] = {&ui_img_phonebluee40_png};
const lv_image_dsc_t* ui_imgset_tools[1] = {&ui_img_tools40_png};
const lv_image_dsc_t* ui_imgset_apps[1] = {&ui_img_apps40_png};
const lv_image_dsc_t* ui_imgset_bg[5] = {&ui_img_bg1_png, &ui_img_bg2_png,
                                         &ui_img_bg3_png, &ui_img_bg4_png,
                                         &ui_img_bg5_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_lblHomeTime(lv_event_t* e) {
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t* target = lv_event_get_target(e);
  if (event_code == LV_EVENT_CLICKED) {
    _ui_screen_change(&ui_alarmMainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0,
                      &ui_alarmMainScreen_screen_init);
  }
}
void ui_event_imbClickEvent(lv_event_t* e) {
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t* target = lv_event_get_target(e);

  const char* btnData = (const char*)e->user_data;

  if (event_code == LV_EVENT_CLICKED) {
    if (strcmp(btnData, "phone") == 0) {
      _ui_screen_change(&ui_mainMenuScreen, LV_SCR_LOAD_ANIM_MOVE_TOP, 300, 0,
                        &ui_mainMenuScreen_screen_init);
    } else if (strcmp(btnData, "home phone") == 0) {
      _ui_screen_change(&ui_mainMenuScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 300, 0,
                        &ui_mainMenuScreen_screen_init);
    } else if (strcmp(btnData, "messages") == 0) {
      _ui_screen_change(&ui_mainMenuScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 300, 0,
                        &ui_mainMenuScreen_screen_init);
    } else if (strcmp(btnData, "home messages") == 0) {
      _ui_screen_change(&ui_mainMenuScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 300, 0,
                        &ui_mainMenuScreen_screen_init);
    } else if (strcmp(btnData, "apps") == 0) {
      _ui_screen_change(&ui_mainMenuScreen, LV_SCR_LOAD_ANIM_MOVE_TOP, 300, 0,
                        &ui_mainMenuScreen_screen_init);
    } else if (strcmp(btnData, "browser") == 0) {
      _ui_screen_change(&ui_contactsScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 300, 0,
                        &ui_contactsScreen_screen_init);
    } else if (strcmp(btnData, "home browser") == 0) {
      _ui_screen_change(&ui_mainMenuScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 300, 0,
                        &ui_mainMenuScreen_screen_init);
    } else if (strcmp(btnData, "contacts") == 0) {
      _ui_screen_change(&ui_contactsScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 300, 0,
                        &ui_contactsScreen_screen_init);
    } else if (strcmp(btnData, "home contacts") == 0) {
      _ui_screen_change(&ui_contactsScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 300, 0,
                        &ui_contactsScreen_screen_init);
    } else if (strcmp(btnData, "multimedia") == 0) {
      _ui_screen_change(&ui_mainMenuScreen, LV_SCR_LOAD_ANIM_MOVE_TOP, 300, 0,
                        &ui_mainMenuScreen_screen_init);
    } else if (strcmp(btnData, "extra") == 0) {
      _ui_screen_change(&ui_mainMenuScreen, LV_SCR_LOAD_ANIM_MOVE_TOP, 300, 0,
                        &ui_mainMenuScreen_screen_init);
    } else if (strcmp(btnData, "games") == 0) {
      _ui_screen_change(&ui_mainMenuScreen, LV_SCR_LOAD_ANIM_MOVE_TOP, 300, 0,
                        &ui_mainMenuScreen_screen_init);
    } else if (strcmp(btnData, "myzone") == 0) {
      _ui_screen_change(&ui_mainMenuScreen, LV_SCR_LOAD_ANIM_MOVE_TOP, 300, 0,
                        &ui_mainMenuScreen_screen_init);
    } else if (strcmp(btnData, "about") == 0) {
      _ui_screen_change(&ui_mainMenuScreen, LV_SCR_LOAD_ANIM_MOVE_TOP, 300, 0,
                        &ui_mainMenuScreen_screen_init);
    } else if (strcmp(btnData, "tools") == 0) {
      _ui_screen_change(&ui_contactsScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 300, 0,
                        &ui_contactsScreen_screen_init);
    }
  }
}
void ui_event_lblHomeContacts(lv_event_t* e) {
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t* target = lv_event_get_target(e);
  if (event_code == LV_EVENT_CLICKED) {
    _ui_screen_change(&ui_contactsScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 300, 0,
                      &ui_contactsScreen_screen_init);
  }
}
void ui_event_evtBottombar(lv_event_t* e) {
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t* target = lv_event_get_target(e);
  const char* btnData = (const char*)e->user_data;

  if (event_code == LV_EVENT_CLICKED) {
    if (strcmp(btnData, "navbar home") == 0) {
      // empty history stack
      _ui_screen_change(&ui_homeScreen, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 300, 0,
                        &ui_homeScreen_screen_init);
    } else if (strcmp(btnData, "navbar back") == 0) {
      // pop history stack
      _ui_screen_change(&ui_homeScreen, LV_SCR_LOAD_ANIM_MOVE_TOP, 300, 0,
                        &ui_homeScreen_screen_init);
    } else if (strcmp(btnData, "navbar tasks") == 0) {
      // complex for now
      _ui_screen_change(&ui_homeScreen, LV_SCR_LOAD_ANIM_MOVE_TOP, 300, 0,
                        &ui_homeScreen_screen_init);
    }
  }
}

void ui_event_lblContactBack(lv_event_t* e) {
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t* target = lv_event_get_target(e);
  if (event_code == LV_EVENT_CLICKED) {
    _ui_screen_change(&ui_homeScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 300, 0,
                      &ui_homeScreen_screen_init);
  }
}

void ui_event_fabContactAdd(lv_event_t* e) {
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t* floatButton = lv_event_get_target(e);

  if (event_code == LV_EVENT_CLICKED) {
    _ui_screen_change(&ui_contactAddScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 300, 0,
                      &ui_contactAddScreen_screen_init);
  }
}

void ui_event_lblContactAddSave(lv_event_t* e) {
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t* target = lv_event_get_target(e);

  if (event_code == LV_EVENT_CLICKED) {
    // TODO: will save the contact
    _ui_screen_change(&ui_contactsScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 300, 0,
                      &ui_contactsScreen_screen_init);
  }
}

void ui_event_lblContactAddDiscard(lv_event_t* e) {
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t* target = lv_event_get_target(e);

  if (event_code == LV_EVENT_CLICKED) {
    _ui_screen_change(&ui_contactsScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 300, 0,
                      &ui_contactsScreen_screen_init);
  }
}

void ui_event_listContact(lv_event_t* e) {
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t* target = lv_event_get_target(e);
  if (event_code == LV_EVENT_CLICKED) {
    const char* contact = lv_list_get_button_text(ui_listContact, target);
    char contactData[CONTACT_NAME_NUMBER_LENGTH];
    strcpy(contactData, contact);

    char* token;
    // FIXME: Handle words separated by " "
    token = strtok(contactData, contactSeparationDelimeter);
    // token = strsep(&contactData, contactSeparationDelimeter);
    if (token != NULL) {
      strlcpy(contactName, token, sizeof(contactName));
      token = strtok(NULL, contactSeparationDelimeter);
      // token = strsep(&contactData, NULL);
      if (token != NULL) {
        strlcpy(contactNumber, token, sizeof(contactNumber));
      }
    }
    _ui_screen_change(&ui_contactDetailsScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 300,
                      0, &ui_contactDetailsScreen_screen_init);
    lv_label_set_text(ui_lblContactDetailsTitle, (const char*)contactName);
  }
}

void ui_event_lblContactDetailsBack(lv_event_t* e) {
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t* target = lv_event_get_target(e);
  if (event_code == LV_EVENT_CLICKED) {
    _ui_screen_change(&ui_contactsScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 300, 0,
                      &ui_contactDetailsScreen_screen_init);
  }
}

void ui_event_listContactDetailsOptions(lv_event_t* e) {
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t* target = lv_event_get_target(e);
  if (event_code == LV_EVENT_CLICKED) {
    LV_LOG_USER("Clicked", lv_list_get_button_text(target));
  }
}

void ui_event_btnOkPinPinScreen(lv_event_t* e) {
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t* target = lv_event_get_target(e);
  if (event_code == LV_EVENT_CLICKED) {
    _ui_screen_change(&ui_homeScreen, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 300, 0,
                      &ui_homeScreen_screen_init);
  }
}

void ui_event_btnMatrixNumHandler(lv_event_t* e) {
  lv_obj_t* obj = lv_event_get_target(e);
  lv_obj_t* uData = lv_event_get_user_data(e);
  const char* txt = lv_buttonmatrix_get_button_text(
      obj, lv_buttonmatrix_get_selected_button(obj));

  if (lv_strcmp(txt, LV_SYMBOL_BACKSPACE) == 0)
    lv_textarea_delete_char(uData);
  else if (lv_strcmp(txt, LV_SYMBOL_NEW_LINE) == 0)
    lv_obj_send_event(uData, LV_EVENT_READY, NULL);
  else
    lv_textarea_add_text(uData, txt);
}

// General events
void ui_event_textArea_full_cb(lv_event_t* e) {
  lv_event_code_t code = lv_event_get_code(e);
  lv_obj_t* ta = lv_event_get_target(e);
  if (code == LV_EVENT_CLICKED) {
    if (ui_keyboard_full == NULL) {
      ui_keyboard_full = lv_keyboard_create(lv_scr_act());
      lv_obj_add_event_cb(ui_keyboard_full, ui_event_keyboard_full_event_cb,
                          LV_EVENT_ALL, NULL);
    }
    lv_keyboard_set_textarea(ui_keyboard_full, ta);
  }

  if (code == LV_EVENT_DEFOCUSED) {
    if (ui_keyboard_full) {
      lv_obj_del(ui_keyboard_full);
      ui_keyboard_full = NULL;
    }
  }
}

void ui_event_textArea_num_cb(lv_event_t* e) {
  lv_event_code_t code = lv_event_get_code(e);
  lv_obj_t* ta = lv_event_get_target(e);

  if (code == LV_EVENT_CLICKED) {
    if (ui_keyboard_num == NULL) {
      ui_keyboard_num = lv_keyboard_create(lv_scr_act());
      lv_obj_add_event_cb(ui_keyboard_num, ui_event_keyboard_num_event_cb,
                          LV_EVENT_ALL, NULL);
      lv_keyboard_set_mode(ui_keyboard_num, LV_KEYBOARD_MODE_NUMBER);
    }
    lv_keyboard_set_textarea(ui_keyboard_num, ta);
  }

  if (code == LV_EVENT_DEFOCUSED) {
    if (ui_keyboard_num) {
      lv_obj_del(ui_keyboard_num);
      ui_keyboard_num = NULL;
    }
  }
}

void ui_event_keyboard_full_event_cb(lv_event_t* e) {
  lv_event_code_t code = lv_event_get_code(e);

  if (code == LV_EVENT_READY || code == LV_EVENT_CANCEL) {
    lv_obj_del(ui_keyboard_full);
    ui_keyboard_full = NULL;
  }
}

void ui_event_keyboard_num_event_cb(lv_event_t* e) {
  lv_event_code_t code = lv_event_get_code(e);

  if (code == LV_EVENT_READY || code == LV_EVENT_CANCEL) {
    lv_obj_del(ui_keyboard_num);
    ui_keyboard_num = NULL;
  }
}
///////////////////// SCREENS ////////////////////

void ui_init(void) {
  lv_disp_t* dispp = lv_display_get_default();
  lv_theme_t* theme = lv_theme_default_init(
      dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
      false, LV_FONT_DEFAULT);
  lv_disp_set_theme(dispp, theme);
  ui_homeScreen_screen_init();
  ui_mainMenuScreen_screen_init();
  ui_contactsScreen_screen_init();
  ui_alarmMainScreen_screen_init();
  ui_simPinScreen_screen_init();
  ui_splashScreen_screen_init();
  ui_contactAddScreen_screen_init();
  ui_contactDetailsScreen_screen_init();
  ui____initial_actions0 = lv_obj_create(NULL);
  lv_disp_load_scr(ui_homeScreen);
}
