// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: s3-phone

#include "ui.h"

void ui_alarmMainScreen_screen_init(void)
{
    ui_alarmMainScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_alarmMainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags


}
