// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: s3-phone

#include "ui.h"

void ui_browserScreen_screen_init(void) {
  ui_browserScreen = lv_obj_create(NULL);
  lv_obj_remove_flag(ui_browserScreen, LV_OBJ_FLAG_SCROLLABLE);  /// Flags

  ui_panelBrowserMain = lv_obj_create(ui_browserScreen);
  lv_obj_set_width(ui_panelBrowserMain, 240);
  lv_obj_set_height(ui_panelBrowserMain, 320);
  lv_obj_remove_flag(ui_panelBrowserMain, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  lv_obj_set_style_bg_image_src(ui_panelBrowserMain, screenWallpaperImg,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_image_opa(ui_panelBrowserMain, 100,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_color(ui_panelBrowserMain, lv_color_hex(0x000000),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_opa(ui_panelBrowserMain, 0,
                              LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_add_bottom_bar(ui_panelBrowserMain, 0xFFFFFF, 10);
}
