// #include "ui.h"

// void ui_contactDetailsScreen_screen_init(void) {
//   ui_contactDetailsScreen = lv_obj_create(NULL);
//   lv_obj_remove_flag(ui_contactDetailsScreen,
//                      LV_OBJ_FLAG_SCROLLABLE);  /// Flags

//   ui_panelContactDetails = lv_obj_create(ui_contactDetailsScreen);
//   lv_obj_set_width(ui_panelContactDetails, 239);
//   lv_obj_set_height(ui_panelContactDetails, 319);
//   lv_obj_set_align(ui_panelContactDetails, LV_ALIGN_CENTER);
//   lv_obj_remove_flag(ui_panelContactDetails, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
//   lv_obj_set_style_bg_color(ui_panelContactDetails, lv_color_hex(0xFFFFFF),
//                             LV_PART_MAIN | LV_STATE_DEFAULT);
//   lv_obj_set_style_bg_opa(ui_panelContactDetails, 0,
//                           LV_PART_MAIN | LV_STATE_DEFAULT);
//   lv_obj_set_style_border_color(ui_panelContactDetails, lv_color_hex(0x000000),
//                                 LV_PART_MAIN | LV_STATE_DEFAULT);
//   lv_obj_set_style_border_opa(ui_panelContactDetails, 255,
//                               LV_PART_MAIN | LV_STATE_DEFAULT);
//   lv_obj_set_style_border_width(ui_panelContactDetails, 1,
//                                 LV_PART_MAIN | LV_STATE_DEFAULT);
//   lv_obj_set_style_radius(ui_panelContactDetails, 0,
//                           LV_PART_MAIN | LV_STATE_DEFAULT);

//   ui_lblContactDetailsTitle = lv_label_create(ui_panelContactDetails);
//   lv_obj_set_width(ui_lblContactDetailsTitle, LV_SIZE_CONTENT);   /// 1
//   lv_obj_set_height(ui_lblContactDetailsTitle, LV_SIZE_CONTENT);  /// 1
//   lv_obj_set_x(ui_lblContactDetailsTitle, 82);
//   lv_obj_set_y(ui_lblContactDetailsTitle, -145);
//   lv_obj_set_align(ui_lblContactDetailsTitle, LV_ALIGN_CENTER);
//   lv_label_set_text(ui_lblContactDetailsTitle, "Contacts");
//   lv_obj_add_flag(ui_lblContactDetailsTitle, LV_OBJ_FLAG_CLICKABLE);  /// Flags
//   lv_obj_set_style_text_color(ui_lblContactDetailsTitle, lv_color_hex(0xFFFFFF),
//                               LV_PART_MAIN | LV_STATE_DEFAULT);
//   lv_obj_set_style_text_opa(ui_lblContactDetailsTitle, 255,
//                             LV_PART_MAIN | LV_STATE_DEFAULT);

//   ui_lblContactDetailsBack = lv_label_create(ui_panelContactDetails);
//   //   lv_obj_set_width(ui_lblContactDetailsBack, LV_SIZE_CONTENT);   /// 1
//   //   lv_obj_set_height(ui_lblContactDetailsBack, LV_SIZE_CONTENT);  /// 1
//     lv_obj_set_x(ui_lblContactDetailsBack, 95);
//     lv_obj_set_y(ui_lblContactDetailsBack, 145);
//   lv_obj_set_align(ui_lblContactDetailsBack, LV_ALIGN_CENTER);
//   lv_obj_add_flag(ui_lblContactDetailsBack, LV_OBJ_FLAG_CLICKABLE);  ///  Flags
//   lv_label_set_text(ui_lblContactDetailsBack, "Back");
//   lv_obj_set_style_text_color(ui_lblContactDetailsBack, lv_color_hex(0x000000),
//                               LV_PART_MAIN | LV_STATE_DEFAULT);
//   lv_obj_add_event_cb(ui_lblContactDetailsBack, ui_event_lblContactDetailsBack,
//                       LV_EVENT_ALL, NULL);
// }

// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: s3-phone

#include "ui.h"

void ui_contactDetailsScreen_screen_init(void) {
  ui_contactDetailsScreen = lv_obj_create(NULL);
  lv_obj_remove_flag(ui_contactDetailsScreen,
                     LV_OBJ_FLAG_SCROLLABLE);  /// Flags

  ui_panelContactDetails = lv_obj_create(ui_contactDetailsScreen);
  lv_obj_set_width(ui_panelContactDetails, 239);
  lv_obj_set_height(ui_panelContactDetails, 319);
  lv_obj_set_align(ui_panelContactDetails, LV_ALIGN_CENTER);
  lv_obj_remove_flag(ui_panelContactDetails, LV_OBJ_FLAG_SCROLLABLE);  /// Flags

  ui_lblContactDetailsTitle = lv_label_create(ui_panelContactDetails);
  lv_obj_set_width(ui_lblContactDetailsTitle, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_lblContactDetailsTitle, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_lblContactDetailsTitle, 0);
  lv_obj_set_y(ui_lblContactDetailsTitle, -145);
  lv_obj_set_align(ui_lblContactDetailsTitle, LV_ALIGN_CENTER);
  lv_label_set_text(ui_lblContactDetailsTitle, "Contact Name");

  ui_lblContactDetailsBack = lv_label_create(ui_panelContactDetails);
  lv_obj_set_width(ui_lblContactDetailsBack, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_lblContactDetailsBack, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_lblContactDetailsBack, 95);
  lv_obj_set_y(ui_lblContactDetailsBack, 145);
  lv_obj_set_align(ui_lblContactDetailsBack, LV_ALIGN_CENTER);
  lv_label_set_text(ui_lblContactDetailsBack, "Back");
  lv_obj_add_flag(ui_lblContactDetailsBack, LV_OBJ_FLAG_CLICKABLE);  /// Flags


  lv_obj_add_event_cb(ui_lblContactDetailsBack, ui_event_lblContactDetailsBack,
                        LV_EVENT_ALL, NULL);
}