// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: s3-phone

#include "ui.h"
#include "ui_contacts.h"
#include "ui_utils.h"

void ui_contactsScreen_screen_init(void) {
  ui_contactsScreen = lv_obj_create(NULL);
  lv_obj_remove_flag(ui_contactsScreen, LV_OBJ_FLAG_SCROLLABLE);  /// Flags

  ui_panelContactMain = lv_obj_create(ui_contactsScreen);
  lv_obj_set_width(ui_panelContactMain, 240);
  lv_obj_set_height(ui_panelContactMain, 320);
  lv_obj_set_align(ui_panelContactMain, LV_ALIGN_TOP_LEFT);
  lv_obj_remove_flag(ui_panelContactMain, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  lv_obj_set_style_bg_color(
      ui_panelContactMain, lv_color_hex(0xFF00FF),
      LV_PART_MAIN | LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_panelContactMain, 100,
                          LV_PART_MAIN | LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
  lv_obj_set_style_border_color(ui_panelContactMain, lv_color_hex(0x000000),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_opa(ui_panelContactMain, 0,
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_radius(ui_panelContactMain, 0,
                          LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_image_src(ui_panelContactMain, screenWallpaperImg,
                                LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_image_src(ui_panelContactMain, screenWallpaperImg,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_image_opa(ui_panelContactMain, 100,
                                LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_lblContactTitle = lv_label_create(ui_panelContactMain);
  lv_label_set_text(ui_lblContactTitle, "Contacts");
  // lv_obj_set_width(ui_lblContactTitle, 40);
  // lv_obj_set_height(ui_lblContactTitle, 20);
  lv_obj_set_x(ui_lblContactTitle, 0);
  lv_obj_set_y(ui_lblContactTitle, UI_ALIGN_TOP_LEFT_Y_OFFSET);
  lv_obj_set_align(ui_lblContactTitle, LV_ALIGN_TOP_MID);
  lv_obj_set_style_text_color(ui_lblContactTitle, lv_color_hex(0x000000),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_lblContactTitle, 255,
                            LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_lblContactTitle, &lv_font_montserrat_16,
                             LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_letter_space(ui_lblContactTitle, 2,
                                     LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_line_space(ui_lblContactTitle, 2,
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_lblContactTitle, LV_TEXT_ALIGN_CENTER,
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_decor(ui_lblContactTitle, LV_TEXT_DECOR_NONE,
                              LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_listContact = lv_list_create(ui_panelContactMain);
  lv_obj_set_width(ui_listContact, 240);
  lv_obj_set_height(ui_listContact, 265);
  lv_obj_set_x(ui_listContact, 0);
  lv_obj_set_y(ui_listContact, 5);
  lv_obj_set_align(ui_listContact, LV_ALIGN_TOP_LEFT);
  lv_obj_set_style_radius(ui_listContact, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  // lv_obj_set_style_bg_color(ui_listContact, lv_color_hex(0xF00000),
  //                           LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_listContact, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_color(ui_listContact, lv_color_hex(0x000000),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_opa(ui_listContact, 255,
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_width(ui_listContact, 0,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_side(ui_listContact, LV_BORDER_SIDE_NONE,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_center(ui_listContact);

  // Populate with contacts
  contact_set_contact_list(ui_listContact);

  lv_obj_t* float_btn = lv_button_create(ui_listContact);
  lv_obj_set_size(float_btn, 40, 40);
  lv_obj_add_flag(float_btn, LV_OBJ_FLAG_FLOATING);
  lv_obj_align(
      float_btn, LV_ALIGN_BOTTOM_RIGHT, 0,
      /*-lv_obj_get_style_pad_right(ui_listContact, LV_PART_MAIN)*/ -5);
  lv_obj_set_style_radius(float_btn, LV_RADIUS_CIRCLE, 0);
  lv_obj_set_style_bg_image_src(float_btn, LV_SYMBOL_PLUS, 0);
  lv_obj_set_style_text_font(float_btn, lv_theme_get_font_large(float_btn), 0);
  lv_obj_add_event_cb(float_btn, ui_event_fab_cb, LV_EVENT_ALL, ui_listContact);

  // navigation buttons
  ui_add_bottom_bar(ui_panelContactMain, 0xFFFFFF, 10);
}
