// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: s3-phone

#include "ui.h"

void ui_contactAddScreen_screen_init(void) {
  ui_contactAddScreen = lv_obj_create(NULL);
  lv_obj_remove_flag(ui_contactAddScreen, LV_OBJ_FLAG_SCROLLABLE);  /// Flags

  ui_contactAddPanel = lv_obj_create(ui_contactAddScreen);
  lv_obj_set_width(ui_contactAddPanel, 239);
  lv_obj_set_height(ui_contactAddPanel, 319);
  lv_obj_set_align(ui_contactAddPanel, LV_ALIGN_CENTER);
  lv_obj_remove_flag(ui_contactAddPanel, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  lv_obj_set_style_border_color(ui_contactAddPanel, lv_color_hex(0x000000),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_opa(ui_contactAddPanel, 255,
                              LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_lblContactAddName = lv_label_create(ui_contactAddPanel);
  lv_obj_set_width(ui_lblContactAddName, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_lblContactAddName, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_lblContactAddName, -91);
  lv_obj_set_y(ui_lblContactAddName, -130);
  lv_obj_set_align(ui_lblContactAddName, LV_ALIGN_CENTER);
  lv_label_set_text(ui_lblContactAddName, "Name");

  ui_txtContactAddName = lv_textarea_create(ui_contactAddPanel);
  lv_obj_set_width(ui_txtContactAddName, 155);
  lv_obj_set_height(ui_txtContactAddName, 36);
  lv_obj_set_x(ui_txtContactAddName, 30);
  lv_obj_set_y(ui_txtContactAddName, -130);
  lv_obj_set_align(ui_txtContactAddName, LV_ALIGN_CENTER);
  lv_textarea_set_placeholder_text(ui_txtContactAddName, "Name...");
  lv_obj_add_event_cb(ui_txtContactAddName, ui_event_textArea_cb, LV_EVENT_ALL,
                      NULL);

  ui_lblContactAddNumber = lv_label_create(ui_contactAddPanel);
  lv_obj_set_width(ui_lblContactAddNumber, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_lblContactAddNumber, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_lblContactAddNumber, -81);
  lv_obj_set_y(ui_lblContactAddNumber, -85);
  lv_obj_set_align(ui_lblContactAddNumber, LV_ALIGN_CENTER);
  lv_label_set_text(ui_lblContactAddNumber, "Number");

  ui_txtContactAddNumber = lv_textarea_create(ui_contactAddPanel);
  lv_obj_set_width(ui_txtContactAddNumber, 155);
  lv_obj_set_height(ui_txtContactAddNumber, 36);
  lv_obj_set_x(ui_txtContactAddNumber, 30);
  lv_obj_set_y(ui_txtContactAddNumber, -85);
  lv_obj_set_align(ui_txtContactAddNumber, LV_ALIGN_CENTER);
  lv_textarea_set_placeholder_text(ui_txtContactAddNumber, "Number...");
  lv_obj_add_event_cb(ui_txtContactAddNumber, ui_event_textArea_cb,
                      LV_EVENT_ALL, NULL);

  ui_lblContactAddSaveTo = lv_label_create(ui_contactAddPanel);
  lv_obj_set_width(ui_lblContactAddSaveTo, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_lblContactAddSaveTo, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_lblContactAddSaveTo, -84);
  lv_obj_set_y(ui_lblContactAddSaveTo, -45);
  lv_obj_set_align(ui_lblContactAddSaveTo, LV_ALIGN_CENTER);
  lv_label_set_text(ui_lblContactAddSaveTo, "Save To");

  ui_dropDownContactAddSaveTo = lv_dropdown_create(ui_contactAddPanel);
  lv_dropdown_set_options(ui_dropDownContactAddSaveTo,
                          "SIM Card\nInternal Storage");
  lv_obj_set_width(ui_dropDownContactAddSaveTo, 155);
  lv_obj_set_height(ui_dropDownContactAddSaveTo, 36);
  lv_obj_set_x(ui_dropDownContactAddSaveTo, 30);
  lv_obj_set_y(ui_dropDownContactAddSaveTo, -40);
  lv_obj_set_align(ui_dropDownContactAddSaveTo, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_dropDownContactAddSaveTo,
                  LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags

  // function buttons
  ui_lblContactAddSave = lv_label_create(ui_contactAddPanel);
  lv_obj_set_align(ui_lblContactAddSave, LV_ALIGN_BOTTOM_LEFT);
  lv_obj_add_flag(ui_lblContactAddSave, LV_OBJ_FLAG_CLICKABLE);  /// Flags
  lv_label_set_text(ui_lblContactAddSave, "Save");
  lv_obj_set_style_text_color(ui_lblContactAddSave, lv_color_hex(0x20FF13),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_add_event_cb(ui_lblContactAddSave, ui_event_lblContactAddSave,
                      LV_EVENT_ALL, NULL);

  ui_lblContactAddBack = lv_label_create(ui_contactAddPanel);
  lv_obj_set_align(ui_lblContactAddBack, LV_ALIGN_BOTTOM_RIGHT);
  lv_obj_add_flag(ui_lblContactAddBack, LV_OBJ_FLAG_CLICKABLE);  /// Flags
  lv_label_set_text(ui_lblContactAddBack, "Discard");
  lv_obj_set_style_text_color(ui_lblContactAddBack, lv_color_hex(0xFF0000),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_add_event_cb(ui_lblContactAddBack, ui_event_lblContactAddDiscard,
                      LV_EVENT_ALL, NULL);
}
