// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: s3-phone

#include "ui.h"

void ui_contactsScreen_screen_init(void) {
  ui_contactsScreen = lv_obj_create(NULL);
  lv_obj_remove_flag(ui_contactsScreen, LV_OBJ_FLAG_SCROLLABLE);  /// Flags

  ui_panelContactMain = lv_obj_create(ui_contactsScreen);
  lv_obj_set_width(ui_panelContactMain, 239);
  lv_obj_set_height(ui_panelContactMain, 319);
  lv_obj_set_align(ui_panelContactMain, LV_ALIGN_CENTER);
  lv_obj_remove_flag(ui_panelContactMain, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  lv_obj_set_style_bg_color(ui_panelContactMain, lv_color_hex(0xFFFFFF),
                            LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_panelContactMain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_color(ui_panelContactMain, lv_color_hex(0x000000),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_opa(ui_panelContactMain, 255,
                              LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_set_style_radius(ui_panelContactMain, 0,
                          LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_panelContactMain, lv_color_hex(0xFFFFFF),
                            LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_panelContactMain, 0,
                          LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_image_src(ui_panelContactMain, &ui_img_nature_png,
                                LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_lblContactTitle = lv_label_create(ui_panelContactMain);
    lv_label_set_text(ui_lblContactTitle, "Contacts");
    lv_obj_set_width(ui_lblContactTitle, 40);
    lv_obj_set_height(ui_lblContactTitle, 20);
    lv_obj_set_x(ui_lblContactTitle, 70);
    lv_obj_set_y(ui_lblContactTitle, 145);
    lv_obj_set_align(ui_lblContactTitle, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_lblContactTitle, lv_color_hex(0x000000),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblContactTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblContactTitle, &lv_font_montserrat_16,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_lblContactTitle, 2,
                                       LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_lblContactTitle, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblContactTitle, LV_TEXT_ALIGN_CENTER,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_lblContactTitle, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_listContact = lv_list_create(ui_panelContactMain);
    lv_obj_set_width(ui_listContact, 239);
    lv_obj_set_height(ui_listContact, 279);
    lv_obj_set_x(ui_listContact, 0);
    lv_obj_set_y(ui_listContact, 120);
    lv_obj_set_align(ui_listContact, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_listContact, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_listContact, lv_color_hex(0xFFFFFF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_listContact, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_listContact, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_listContact, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_listContact, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_listContact, LV_BORDER_SIDE_NONE,
                                 LV_PART_MAIN | LV_STATE_DEFAULT);

}
