// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: s3-phone

#include "ui.h"

void ui_filesScreen_screen_init(void) {
  ui_filesScreen = lv_obj_create(NULL);
  lv_obj_remove_flag(ui_filesScreen, LV_OBJ_FLAG_SCROLLABLE);  /// Flags

  ui_panelFilesMain = lv_obj_create(ui_filesScreen);
  lv_obj_set_width(ui_panelFilesMain, 240);
  lv_obj_set_height(ui_panelFilesMain, 320);
  lv_obj_remove_flag(ui_panelFilesMain, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  lv_obj_set_style_bg_image_src(ui_panelFilesMain, screenWallpaperImg,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_image_opa(ui_panelFilesMain, 100,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_color(ui_panelFilesMain, lv_color_hex(0x000000),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_opa(ui_panelFilesMain, 0,
                              LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_add_bottom_bar(ui_panelFilesMain, 0xFFFFFF, 10);
}
