// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: s3-phone

#include "ui.h"

void ui_gamesScreen_screen_init(void) {
  ui_gamesScreen = lv_obj_create(NULL);
  lv_obj_remove_flag(ui_gamesScreen, LV_OBJ_FLAG_SCROLLABLE);  /// Flags

  ui_panelGamesMain = lv_obj_create(ui_gamesScreen);
  lv_obj_set_width(ui_panelGamesMain, 240);
  lv_obj_set_height(ui_panelGamesMain, 320);
  lv_obj_remove_flag(ui_panelGamesMain, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  lv_obj_set_style_bg_image_src(ui_panelGamesMain, screenWallpaperImg,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_image_opa(ui_panelGamesMain, 100,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_color(ui_panelGamesMain, lv_color_hex(0x000000),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_opa(ui_panelGamesMain, 0,
                              LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_add_bottom_bar(ui_panelGamesMain, 0xFFFFFF, 10);
}
