// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: s3-phone

#include "ui.h"

void ui_multimediaScreen_screen_init(void) {
  ui_multimediaScreen = lv_obj_create(NULL);
  lv_obj_remove_flag(ui_multimediaScreen, LV_OBJ_FLAG_SCROLLABLE);  /// Flags

  ui_panelMultimediaMain = lv_obj_create(ui_multimediaScreen);
  lv_obj_set_width(ui_panelMultimediaMain, 240);
  lv_obj_set_height(ui_panelMultimediaMain, 320);
  lv_obj_remove_flag(ui_panelMultimediaMain, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  lv_obj_set_style_bg_image_src(ui_panelMultimediaMain, screenWallpaperImg,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_image_opa(ui_panelMultimediaMain, 100,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_color(ui_panelMultimediaMain, lv_color_hex(0x000000),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_opa(ui_panelMultimediaMain, 0,
                              LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_add_bottom_bar(ui_panelMultimediaMain, 0xFFFFFF, 10);
}
