// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: s3-phone

#include "ui.h"

void ui_splashScreen_screen_init(void)
{
    ui_splashScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_splashScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_splashScreen, lv_color_hex(0x171826), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_splashScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // TODO: find a way to work with lottie animations
    lv_obj_t* gifLoadAnim;
    gifLoadAnim = lv_gif_create(ui_splashScreen);
    lv_obj_set_width(gifLoadAnim, 240);
    lv_obj_set_height(gifLoadAnim, 240);
    lv_gif_set_src(gifLoadAnim, &ui_lottie_load_circular);
    // lv_gif_set_src(gifLoadAnim, "A:/load_circular.gif");
    lv_obj_set_align(gifLoadAnim, LV_ALIGN_CENTER);
    // lv_gif_restart(gifLoadAnim);
}
