// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: s3-phone

#include "ui.h"

char settingsOptions[][30] = {"Connectivity",
                              "Network and Internet",
                              "Display",
                              "Wallpapers and Themes",
                              "Lock Screen and Security",
                              "Sounds",
                              "Storage",
                              "System",
                              "About"};

void populate_list_from_array(lv_obj_t *list);
void ui_event_list_event_callback(lv_event_t *e);
void option_add_to_list(lv_obj_t *list, const char *text,
                        const char *symbol_icon, lv_event_cb_t event_cb,
                        lv_event_code_t event_filter, void *user_data);

void ui_settingsMainScreen_screen_init(void) {
  ui_settingsMainScreen = lv_obj_create(NULL);
  lv_obj_remove_flag(ui_settingsMainScreen, LV_OBJ_FLAG_SCROLLABLE);  /// Flags

  ui_panelSettingsMain = lv_obj_create(ui_settingsMainScreen);
  lv_obj_set_width(ui_panelSettingsMain, 240);
  lv_obj_set_height(ui_panelSettingsMain, 320);
  lv_obj_remove_flag(ui_panelSettingsMain, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  lv_obj_set_style_bg_image_src(ui_panelSettingsMain, screenWallpaperImg,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_image_opa(ui_panelSettingsMain, 100,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_color(ui_panelSettingsMain, lv_color_hex(0x000000),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_opa(ui_panelSettingsMain, 0,
                              LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_t *lblTitle = lv_label_create(ui_panelSettingsMain);
  lv_obj_set_align(lblTitle, LV_ALIGN_TOP_MID);
  lv_obj_set_x(lblTitle, 0);
  lv_obj_set_y(lblTitle, UI_ALIGN_TOP_LEFT_Y_OFFSET);
  lv_label_set_text(lblTitle, "Settings");
  lv_obj_set_style_text_color(lblTitle, lv_color_hex(0x000000),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(lblTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(lblTitle, &lv_font_montserrat_18,
                             LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_letter_space(lblTitle, 2,
                                     LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_line_space(lblTitle, 2,
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(lblTitle, LV_TEXT_ALIGN_CENTER,
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_decor(lblTitle, LV_TEXT_DECOR_NONE,
                              LV_PART_MAIN | LV_STATE_DEFAULT);

  // list for settings menu
  listSettingsOptions = lv_list_create(ui_panelSettingsMain);
  lv_obj_set_width(listSettingsOptions, 240);
  lv_obj_set_height(listSettingsOptions, 265);
  lv_obj_set_x(listSettingsOptions, 0);
  lv_obj_set_y(listSettingsOptions, 5);
  lv_obj_set_align(listSettingsOptions, LV_ALIGN_TOP_LEFT);
  lv_obj_set_style_radius(listSettingsOptions, 0,
                          LV_PART_MAIN | LV_STATE_DEFAULT);
  // lv_obj_set_style_bg_color(listSettingsOptions, lv_color_hex(0xF00000),
  //                           LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(listSettingsOptions, 0,
                          LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_color(listSettingsOptions, lv_color_hex(0x000000),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_opa(listSettingsOptions, 255,
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_width(listSettingsOptions, 0,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_side(listSettingsOptions, LV_BORDER_SIDE_NONE,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_center(listSettingsOptions);

  // populate list
  populate_list_from_array(listSettingsOptions);

  ui_add_bottom_bar(ui_panelSettingsMain, 0xFFFFFF, 10);
}

void populate_list_from_array(lv_obj_t *list) {
  int arrayLength = sizeof(settingsOptions) / sizeof(settingsOptions[0]);
  for (int i = 0; i < arrayLength; i++) {
    option_add_to_list(list, settingsOptions[i], LV_SYMBOL_LIST,
                       ui_event_list_event_callback, LV_EVENT_CLICKED, NULL);
  }
}

void option_add_to_list(lv_obj_t *list, const char *text,
                        const char *symbol_icon, lv_event_cb_t event_cb,
                        lv_event_code_t event_filter, void *user_data) {
  lv_obj_t *btn;
  btn = lv_list_add_button(list, symbol_icon, text);
  lv_obj_set_style_bg_opa(btn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_add_event_cb(btn, event_cb, event_filter /*LV_EVENT_CLICKED*/,
                      user_data /*NULL*/);
}

void ui_event_list_event_callback(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  //   lv_obj_t *list = lv_obj_get_parent(target);

  const char *buttonText = lv_list_get_button_text(listSettingsOptions, target);

  if (event_code == LV_EVENT_CLICKED) {
    if (strcmp(buttonText, "Connectivity") == 0) {
      if (screenStackPush(SCREEN_SETTINGS, ui_settingsMainScreen,
                          &ui_settingsMainScreen_screen_init,
                          LV_SCR_LOAD_ANIM_MOVE_RIGHT)) {
        _ui_screen_change(&ui_settingsConnectivityScreen,
                          LV_SCR_LOAD_ANIM_MOVE_LEFT, UI_ANIMATION_DURATION, 0,
                          &ui_settingsConnectivityScreen_screen_init);
      }
    } else if (strcmp(buttonText, "Network and Internet") == 0) {
      if (screenStackPush(SCREEN_SETTINGS, ui_settingsMainScreen,
                          &ui_settingsMainScreen_screen_init,
                          LV_SCR_LOAD_ANIM_MOVE_RIGHT)) {
        _ui_screen_change(&ui_settingsNetworkInternetScreen,
                          LV_SCR_LOAD_ANIM_MOVE_LEFT, UI_ANIMATION_DURATION, 0,
                          &ui_settingsNetworkInternetScreen_screen_init);
      }
    } else if (strcmp(buttonText, "Display") == 0) {
      if (screenStackPush(SCREEN_SETTINGS, ui_settingsMainScreen,
                          &ui_settingsMainScreen_screen_init,
                          LV_SCR_LOAD_ANIM_MOVE_RIGHT)) {
        _ui_screen_change(&ui_settingsDisplayScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT,
                          UI_ANIMATION_DURATION, 0,
                          &ui_settingsDisplayScreen_screen_init);
      }
    } else if (strcmp(buttonText, "Wallpapers and Themes") == 0) {
      if (screenStackPush(SCREEN_SETTINGS, ui_settingsMainScreen,
                          &ui_settingsMainScreen_screen_init,
                          LV_SCR_LOAD_ANIM_MOVE_RIGHT)) {
        _ui_screen_change(&ui_settingsThemesScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT,
                          UI_ANIMATION_DURATION, 0,
                          &ui_settingsThemesScreen_screen_init);
      }
    } else if (strcmp(buttonText, "Lock Screen and Security") == 0) {
      if (screenStackPush(SCREEN_SETTINGS, ui_settingsMainScreen,
                          &ui_settingsMainScreen_screen_init,
                          LV_SCR_LOAD_ANIM_MOVE_RIGHT)) {
        _ui_screen_change(&ui_settingsLockSecurityScreen,
                          LV_SCR_LOAD_ANIM_MOVE_LEFT, UI_ANIMATION_DURATION, 0,
                          &ui_settingsLockSecurityScreen_screen_init);
      }
    } else if (strcmp(buttonText, "Sounds") == 0) {
      if (screenStackPush(SCREEN_SETTINGS, ui_settingsMainScreen,
                          &ui_settingsMainScreen_screen_init,
                          LV_SCR_LOAD_ANIM_MOVE_RIGHT)) {
        _ui_screen_change(&ui_settingsSoundScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT,
                          UI_ANIMATION_DURATION, 0,
                          &ui_settingsSoundScreen_screen_init);
      }
    } else if (strcmp(buttonText, "Storage") == 0) {
      if (screenStackPush(SCREEN_SETTINGS, ui_settingsMainScreen,
                          &ui_settingsMainScreen_screen_init,
                          LV_SCR_LOAD_ANIM_MOVE_RIGHT)) {
        _ui_screen_change(&ui_settingsStorageScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT,
                          UI_ANIMATION_DURATION, 0,
                          &ui_settingsStorageScreen_screen_init);
      }
    } else if (strcmp(buttonText, "System") == 0) {
      if (screenStackPush(SCREEN_SETTINGS, ui_settingsMainScreen,
                          &ui_settingsMainScreen_screen_init,
                          LV_SCR_LOAD_ANIM_MOVE_RIGHT)) {
        _ui_screen_change(&ui_settingsSystemScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT,
                          UI_ANIMATION_DURATION, 0,
                          &ui_settingsSystemScreen_screen_init);
      }
    } else if (strcmp(buttonText, "About") == 0) {
      if (screenStackPush(SCREEN_SETTINGS, ui_settingsMainScreen,
                          &ui_settingsMainScreen_screen_init,
                          LV_SCR_LOAD_ANIM_MOVE_RIGHT)) {
        _ui_screen_change(&ui_settingsAboutScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT,
                          UI_ANIMATION_DURATION, 0,
                          &ui_settingsAboutScreen_screen_init);
      }
    }
  }
}
