// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: s3-phone

#include "ui.h"

void ui_settingsSystemScreen_screen_init(void) {
  ui_settingsSystemScreen = lv_obj_create(NULL);
  lv_obj_remove_flag(ui_settingsSystemScreen,
                     LV_OBJ_FLAG_SCROLLABLE);  /// Flags

  ui_panelSettingsSystem = lv_obj_create(ui_settingsSystemScreen);
  lv_obj_set_width(ui_panelSettingsSystem, 240);
  lv_obj_set_height(ui_panelSettingsSystem, 320);
  lv_obj_remove_flag(ui_panelSettingsSystem, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  lv_obj_set_style_bg_image_src(ui_panelSettingsSystem, &ui_img_bg1_png,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_image_opa(ui_panelSettingsSystem, 100,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_color(ui_panelSettingsSystem, lv_color_hex(0x000000),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_opa(ui_panelSettingsSystem, 0,
                              LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_add_bottom_bar(ui_panelSettingsSystem, 0xFFFFFF, 10);
}
