// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: s3-phone

#include "ui.h"

void ui_simPinScreen_screen_init(void) {
  ui_simPinScreen = lv_obj_create(NULL);
  lv_obj_remove_flag(ui_simPinScreen, LV_OBJ_FLAG_SCROLLABLE);  /// Flags

  ui_txtPinPinScreen = lv_textarea_create(ui_simPinScreen);
  lv_obj_set_width(ui_txtPinPinScreen, 240);
  lv_obj_set_height(ui_txtPinPinScreen, LV_SIZE_CONTENT);  /// 40
  lv_obj_set_x(ui_txtPinPinScreen, 0);
  lv_obj_set_y(ui_txtPinPinScreen, -110);
  lv_obj_set_align(ui_txtPinPinScreen, LV_ALIGN_CENTER);
  if ("0123456789" == "")
    lv_textarea_set_accepted_chars(ui_txtPinPinScreen, NULL);
  else
    lv_textarea_set_accepted_chars(ui_txtPinPinScreen, "0123456789");
  lv_textarea_set_max_length(ui_txtPinPinScreen, 4);
  lv_textarea_set_placeholder_text(ui_txtPinPinScreen, "Enter SIM PIN");
  lv_textarea_set_one_line(ui_txtPinPinScreen, true);
  lv_textarea_set_password_mode(ui_txtPinPinScreen, true);
  lv_obj_add_state(ui_txtPinPinScreen,
                   LV_STATE_FOCUSED); /*To be sure the cursor is visible*/

  ui_btnOkPinPinScreen = lv_button_create(ui_simPinScreen);
  lv_obj_set_width(ui_btnOkPinPinScreen, 50);
  lv_obj_set_height(ui_btnOkPinPinScreen, 35);
  lv_obj_set_x(ui_btnOkPinPinScreen, 90);
  lv_obj_set_y(ui_btnOkPinPinScreen, 135);
  lv_obj_set_align(ui_btnOkPinPinScreen, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_btnOkPinPinScreen, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  lv_obj_remove_flag(ui_btnOkPinPinScreen, LV_OBJ_FLAG_SCROLLABLE);    /// Flags

  // replaced with a keypad
  //   ui_lblOkPinPinScreen = lv_label_create(ui_btnOkPinPinScreen);
  //   lv_obj_set_width(ui_lblOkPinPinScreen, LV_SIZE_CONTENT);   /// 1
  //   lv_obj_set_height(ui_lblOkPinPinScreen, LV_SIZE_CONTENT);  /// 1
  //   lv_obj_set_align(ui_lblOkPinPinScreen, LV_ALIGN_CENTER);
  //   lv_label_set_text(ui_lblOkPinPinScreen, "OK");

  ui_lblUnlockPhonePinScreen = lv_label_create(ui_simPinScreen);
  lv_obj_set_width(ui_lblUnlockPhonePinScreen, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_lblUnlockPhonePinScreen, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_lblUnlockPhonePinScreen, 0);
  lv_obj_set_y(ui_lblUnlockPhonePinScreen, -145);
  lv_obj_set_align(ui_lblUnlockPhonePinScreen, LV_ALIGN_CENTER);
  lv_label_set_text(ui_lblUnlockPhonePinScreen, "Unlock Phone");
  lv_obj_set_style_text_font(ui_lblUnlockPhonePinScreen, &lv_font_montserrat_20,
                             LV_PART_MAIN | LV_STATE_DEFAULT);

  static const char* btnMatrixNumMap[] = {"1",
                                          "2",
                                          "3",
                                          "\n",
                                          "4",
                                          "5",
                                          "6",
                                          "\n",
                                          "7",
                                          "8",
                                          "9",
                                          "\n",
                                          LV_SYMBOL_BACKSPACE,
                                          "0",
                                          LV_SYMBOL_NEW_LINE,
                                          ""};

  ui_btnMatrixNumPinScreen = lv_buttonmatrix_create(ui_simPinScreen);
  lv_obj_set_size(ui_btnMatrixNumPinScreen, 240, 264);
  lv_obj_set_y(ui_btnMatrixNumPinScreen, 35);
  lv_obj_set_align(ui_btnMatrixNumPinScreen, LV_ALIGN_CENTER);
  lv_obj_add_event_cb(ui_btnMatrixNumPinScreen, ui_event_keyboard_cb,
                      LV_EVENT_VALUE_CHANGED, "sim unlock");
  lv_obj_remove_flag(ui_btnMatrixNumPinScreen,
                     LV_OBJ_FLAG_CLICK_FOCUSABLE); /*To keep the text area
                                                      focused on button clicks*/
  lv_buttonmatrix_set_map(ui_btnMatrixNumPinScreen, btnMatrixNumMap);
}
