// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: s3-phone

#include "ui.h"

void ui_toolsScreen_screen_init(void) {
  ui_toolsScreen = lv_obj_create(NULL);
  lv_obj_remove_flag(ui_toolsScreen, LV_OBJ_FLAG_SCROLLABLE);  /// Flags

  ui_panelToolsMain = lv_obj_create(ui_toolsScreen);
  lv_obj_set_width(ui_panelToolsMain, 240);
  lv_obj_set_height(ui_panelToolsMain, 320);
  lv_obj_remove_flag(ui_panelToolsMain, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  lv_obj_set_style_bg_image_src(ui_panelToolsMain, screenWallpaperImg,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_image_opa(ui_panelToolsMain, 100,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_color(ui_panelToolsMain, lv_color_hex(0x000000),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_opa(ui_panelToolsMain, 0,
                              LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_add_bottom_bar(ui_panelToolsMain, 0xFFFFFF, 10);
}
